//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDWPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fund
    {
        public int FundID { get; set; }
        public decimal TotalAmount { get; set; }
        public Nullable<int> ProgramID { get; set; }
    
        public virtual Program Program { get; set; }
    }
}
