//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDWPF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BFEntities1 : DbContext
    {
        public BFEntities1()
            : base("name=BFEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Beneficiary> Beneficiary { get; set; }
        public virtual DbSet<Donation> Donation { get; set; }
        public virtual DbSet<Donor> Donor { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<Fund> Fund { get; set; }
        public virtual DbSet<Program> Program { get; set; }
        public virtual DbSet<Report> Report { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
