//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDWPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report
    {
        public int ReportID { get; set; }
        public System.DateTime Date { get; set; }
        public string Description { get; set; }
        public Nullable<int> DonationID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
    
        public virtual Donation Donation { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
